Enable ca1068
App-vNext/Polly pull request #1677
Opened 2023-10-04 17:30 UTC by davidCett

# Pull Request

## The issue or feature being addressed

Cleanup the Polly and Polly.Specs codebase #1290

## Details on the issue fix or feature implementation

Enable CA1068 warning (CancellationToken parameters must come last) and code cleanup

## Confirm the following

- [x]  I started this PR by branching from the head of the default branch
- [x]  I have targeted the PR to merge into the default branch
- [ ]  I have included unit tests for the issue/feature
- [x]  I have successfully run a local build

2023-10-04 17:42 UTC, davidCett commented
@dotnet-policy-service agree

2023-10-04 18:54 UTC, martincostello requested changes

2023-10-04 18:54 UTC, martincostello commented on src/Polly/AsyncPolicy.GenericImplementation.cs
> +        bool continueOnCapturedContext,
Just scan reading this PR before a proper review tomorrow, the public API surface area like this **must not** be changed to resolve these warnings. Anything this isn't internal or private must be suppressed only.

Changing the order of the parameters in the public API surface is a breaking change we cannot accept.

2023-10-05 08:11 UTC, martincostello commented
As you can [see in the build log](https://github.com/App-vNext/Polly/actions/runs/6409461852/job/17403157798?pr=1677#step:5:674), the Public API analyser flags the changes to the public surface of the library and breaks the build.

For example:

```
Error: C:\Program Files\dotnet\sdk\7.0.401\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ApiCompat.ValidatePackage.targets(39,5): error CP0002: Member 'Polly.AsyncPolicy.ExecuteAsync(System.Func<System.Threading.CancellationToken, System.Threading.Tasks.Task>, System.Threading.CancellationToken, bool)' exists on [Baseline] lib/net461/Polly.dll but not on lib/netstandard2.0/Polly.dll [D:\a\Polly\Polly\src\Polly\Polly.csproj]
```

2023-10-05 08:12 UTC, martincostello commented on src/Polly/PublicAPI.Shipped.txt
This is the wrong thing to do - the file is effectively set in stone and should not be edited.

2023-10-05 10:40 UTC, davidCett commented on src/Polly/PublicAPI.Shipped.txt
I get it. My bad.

2023-10-05 10:40 UTC, davidCett commented
Thank you for de review. I will work on it😀

2023-12-20 01:40 UTC, closed without merging